homework1.v.0.1
bi-te/DLRenderEngine pull request #1
Opened 2022-04-29 14:04 UTC by bi-te

2022-05-02 13:22 UTC, DmitrySarafaniuk commented
1. Первый раз не собралось, нужно было добавить header/ к инклюдам в Main.cpp. Если есть возможность перед отправкой проверять на другой машине, то сделайте, пожалуйста.
2. Элементы векторов, матриц и т.п. желательно делать с фиксированной точкой, а не целочисленные.
3. Пока делаете свою математику, то лучше выносить операции по типу length, length_squared, чтобы легче можно было использовать существующие функции (например, умножение или dot, если бы он был, можно использовать в функции length). То есть вектор, матрицу и т.д. реализовать с уклонов в представление данных, а функции над ними выделять отдельно. Когда будет DirectX и разрешат использовать сторонние библиотеки, то лучше на написание своей математики время не тратить.
4. Классы с визуальной точки зрения легче распознавать, когда они называются с большой буквы.
5. Пересечение луча и сферы неполное, поэтому просчитывается некорректно (можно выставить z = -90, и её всё равно видно, хотя она находится за камерой).
Перед тем, как переписывать, можно на бумажке получить формулу и посмотреть, что можно сократить или убрать (например, вынести из-под корня множитель, учесть, что вектор всегда нормализован и поэтому его dot или длинна равны 1). 
Такие моменты с упрощением формул могут казаться не критичными, но иногда они помогают. Для nintendo switch выполнение векторных и скалярных операций зачастую времязатратные и иногда даже переход в одной часто используемой функции на intrinsic операции или на сокращенные вычисления может дать прирост в 0.3мс. Просто нужно держать такой вариант в голове.
6. В функцию check_collision было бы неплохо передавать hit_record и записывать туда точку, где луч попал в объект, нормаль поверхности и т.д., вместо того чтобы просто возвращать true или false.
7. В engine.h много разных определений. Пока задание не большое, то это не вызывает сложностей, но при масштабировании нужно будет выносить screen и mouse в другие файлы. 
Тот же вопрос к определению check_collision в engine - действительно ли это хорошее место для этой функции, возможно, ей было бы лучше быть методом sphere.
8. Можно в определении engine не хранить напрямую объекты, которые будут рендериться, а вынести их в какой-то свой класс/контейнер. Вместе с этим можно пересмотреть инициализацию сферы в конструкторе движка и даже задуматься о переносе process_rays в соответствующий класс. 
9. К goto отношусь нейтрально, но замена его на какой-то более стандартный выход из цикла желательна.
10. while(timer.frame_time_check()) можно заменить на if(timer.frame_time_check()), тогда не будет подтормаживаний с инпутом.
11. Положение сферы не обязательно обновлять в WM_MOUSEMOVE, можно попробовать вынести в цикл движка, как это уже сделано с клавиатурой.
12. Чтобы не нагромождать Main.cpp, можно сделать класс Window и работать уже с ним.

Если есть напряг по срокам сдачи, то вот пункты по важности 12, 7, 5, 8, 11, но лучше было бы сделать все.
В целом достойно, программа работает относительно быстро.

2022-05-02 18:57 UTC, mrindieperson commented
Сделай, пожалуйста, как описано в требованиях, папку engine в корне рядом с файлом проекта, и перемести в engine/math/ файлы ray/sphere/vec3, чтобы они лежали отдельно там. Остальные файлы кроме main просто в engine/ положи

2022-05-02 19:05 UTC, mrindieperson commented
Давай добавим поддержку ресайза окна, пожалуйста

2022-05-02 19:12 UTC, mrindieperson requested changes

2022-05-02 19:12 UTC, mrindieperson commented on Main.cpp
> +        while(timer.frame_time_check())
Замени while на if, если рендер слишком долгий, мы не выйдем из цикла и программа перестанет отвечать

2022-05-03 14:04 UTC, bi-te commented on Main.cpp
> +        while(timer.frame_time_check())
++

2022-05-03 15:34 UTC, mrindieperson commented
Отдели реализацию функций от объявления, вынеси код больших функций в .cpp файлы, чтобы в .h были только объявления классов и реализация только маленьких функций в несколько строк, которые компилятор мог бы заинлайнить даже

2022-05-03 16:02 UTC, mrindieperson requested changes

2022-05-03 16:02 UTC, mrindieperson commented on engine/RenderList.h
> +	std::vector<std::shared_ptr<SphereObject>> list;
Нет, мы будем стараться использовать поменьше ООП и будем больше ориентироваться на Data Oriented подход при разработке движка. А что если у нас 10000 сфер в сцене? Во-первых компилятор не может заинлайнить код, когда ему нужно вызвать виртуальные функции, во-вторых CPU придётся скакать по памяти, сначала по адресу shared_ptr, потом по адресу таблицы виртуальных функций. в-третьих будет ещё постоянный оверхед из-за увеличения/уменьшения числа ссылок.

Храни просто vector\<sphere\>.

2022-05-03 16:02 UTC, mrindieperson commented on engine/Engine.h
> +	RenderList world;
RenderList не удачное название.
Давай просто назовём Scene scene;

2022-05-03 16:02 UTC, mrindieperson commented on engine/RenderList.h
> +class RenderList: public RenderObject
Думаю лучше назвать это Scene.
И убери наследование от RenderObject. Виртуальные методы move и ray_collision сейчас не помогают выполнить никакую задачу, это излишний интерфейс ради интерфейса

2022-05-03 16:02 UTC, mrindieperson commented on engine/math/Sphere.h
> +	double radius;
Замени везде double на float, нам такая точность не нужна сейчас

2022-05-03 16:02 UTC, mrindieperson commented on engine/SphereObject.h
> +			if(t  > t_min)
У тебя может быть 1 или 2 валидных решения, когда T больше нуля, то есть точка находится перед лучом, а не сзади. Тебе нужно найти _минимальное_ из _валидных_ значений T и только один раз посчитать значения, которые пишутся в record. Убери таким образом дублирование кода в функции

2022-05-03 16:02 UTC, mrindieperson commented on engine/SphereObject.h
> +class SphereObject: public Sphere, public RenderObject
Этот класс тебе в итоге нужен только чтобы уметь двигать одну сферу. Это не эффективно. Как я написал выше, в сцене нужно хранить только массив простых математических сфер. Этот класс из-за указателя на таблицу виртуальных функций увеличивает размер сферы на лишние 8 байт, то есть в полтора раза (сфера занимает 4 флота, то есть 16 байт). Я уже не буду повторять про то, что все сферы были бы разрознены в памяти из-за shared_ptr.

Я в рамках следующего задания объясню, как решать эту задачу

2022-05-03 16:02 UTC, mrindieperson commented on engine/RenderList.h
> +			if (obj.ray_collision(ray, t_min, result) && result.point.z < prev_z)
Так как у нас будет просто вектор сфер, здесь будет простая итерация по сферам и невиртуальный вызов ray_collision у Sphere. Это было бы не эффективно бегать по 10 тысячам SphereObject и вызывать виртуальные методы только чтобы в итоге подвигать одну сферу. Сделай пока просто перетаскивание сферы прямо в этой функции без вызова всяких виртуальных функций, SphereObject здесь не нужен, только чистая Sphere

2022-05-03 16:02 UTC, mrindieperson commented on engine/RenderList.h
> +			if (obj.ray_collision(ray, t_min, result) && result.point.z < prev_z)
Аналогично тут нужно просто нарисовать примитивные сферы, без всяких виртуальных ray_collision

2022-05-03 16:02 UTC, mrindieperson commented on engine/RayTracer.h
> +	static void process_rays(const RenderObject& object, Screen& screen)
На самом деле этот класс излишен, можно было бы это сделать просто методом Scene::draw, тут даже первым аргументом идёт RenderObject, который на самом деле просто Scene

2022-05-03 16:02 UTC, mrindieperson commented on engine/Engine.h
> +    void process_input(double dt)
Давай поле InputState и processInput метод просто объединим в класс Controller, который будет стоять отдельно. Это будет высокоуровневый класс игровой логики, который внутри себя уже может управлять Scene, имея ссылку на неё. Controller - это project-specific код, а Scene - код движка общего назначения. Controller должен инициализировать и управлять сценой и прочими вещами в проекте, как класс самого верхнего уровня

2022-05-04 06:57 UTC, bi-te commented on engine/RenderList.h
> +	std::vector<std::shared_ptr<SphereObject>> list;
++

2022-05-04 08:08 UTC, bi-te commented on engine/RayTracer.h
> +	static void process_rays(const RenderObject& object, Screen& screen)
++

2022-05-04 08:09 UTC, bi-te commented on engine/RenderList.h
> +			if (obj.ray_collision(ray, t_min, result) && result.point.z < prev_z)
++

2022-05-04 08:09 UTC, bi-te commented on engine/RenderList.h
> +			if (obj.ray_collision(ray, t_min, result) && result.point.z < prev_z)
++

2022-05-04 08:10 UTC, bi-te commented on engine/SphereObject.h
> +class SphereObject: public Sphere, public RenderObject
++

2022-05-04 08:10 UTC, bi-te commented on engine/SphereObject.h
> +			if(t  > t_min)
++

2022-05-04 08:10 UTC, bi-te commented on engine/math/Sphere.h
> +	double radius;
++

2022-05-04 08:10 UTC, bi-te commented on engine/RenderList.h
> +class RenderList: public RenderObject
++

2022-05-04 08:10 UTC, bi-te commented on engine/Engine.h
> +	RenderList world;
++

2022-05-04 11:25 UTC, bi-te commented on engine/Engine.h
> +    void process_input(double dt)
++

2022-05-04 11:39 UTC, mrindieperson commented on engine/Scene.cpp
> +		float D = b * b - 4 * c;
Инкапсулируй весь код пересечения луча и сферы в метод sphere::intersection/hit(ray)

2022-05-04 11:40 UTC, mrindieperson commented on engine/Scene.cpp
> +	float prev_z = DBL_MAX;
std::numeric_limits\<float\>::infinity();

2022-05-04 11:41 UTC, mrindieperson commented on Main.cpp
> +    generate_world();
Сделай это методом Controller::initScene

2022-05-04 11:45 UTC, mrindieperson commented on engine/math/Vec3.h
> +using Point3d = Vec3;
Совсем ненужный алиас, есть же просто Vec3

2022-05-04 11:53 UTC, bi-te commented on engine/Scene.cpp
> +	float prev_z = DBL_MAX;
++

2022-05-04 11:54 UTC, bi-te commented on engine/Scene.cpp
> +		float D = b * b - 4 * c;
++

2022-05-04 11:58 UTC, bi-te commented on Main.cpp
> +    generate_world();
++

2022-05-04 12:00 UTC, bi-te commented on engine/math/Vec3.h
> +using Point3d = Vec3;
Этот алиас скорее просто для удобства, лично мне понятнее когда вижу, что отвечает просто за точку, а что есть вектором.

2022-05-04 12:23 UTC, mrindieperson commented on engine/math/Vec3.h
> +using Point3d = Vec3;
Именно с точки зрения структуры кода это просто лишняя сущность, которая захламляет код. Можешь оставить, если хочешь, но обычно алиасы используют там, где нужно сократить число символов в типе, в шаблонном, например. А иначе у нас будет Vec3, Point3, Direction3 и т.д. :) Но по факту проще разницу между Point3 и Direction3 можно по названием переменной увидеть

2022-05-04 12:25 UTC, mrindieperson approved these changes

2022-05-04 12:33 UTC, DmitrySarafaniuk approved these changes

2022-05-04 12:33 UTC, FantasticMrF0x commented on engine/Engine.h
> +        input_state.mouse.prev_y = input_state.mouse.y;
Эти строки лучше было бы распределить в InputState между Keyboard и Mouse и потом вызывать в Engine (как сделано со screen.resize())

2022-05-04 12:33 UTC, FantasticMrF0x commented on engine/RenderList.h
> +class RenderList: public RenderObject
Не совсем понятно, зачем нужно это наследование

2022-05-04 12:52 UTC, merged