homework3.v.0.1
bi-te/DLRenderEngine pull request #3
Opened 2022-06-14 09:19 UTC by bi-te

2022-06-14 13:24 UTC, DmitrySarafaniuk commented on engine/render/light_render.cpp
> +	const vec3& radiance, float dw, const Material& m)
Назови аргументы более понятно вместо l, cl, v и т.д., пожалуйста.

2022-06-14 13:27 UTC, FantasticMrF0x commented
При зажатии кнопки R сделай, пожалуйста, переключение отражений только один раз, чтобы они за секунду не выключались и включались по несколько раз (игнорировать повторные события, которые для печати текста используются).

2022-06-14 13:38 UTC, DmitrySarafaniuk commented
Замени магические числа на константы (`m.roughness < 0.1f && depth < max_depth` на`m.roughness < MAX_REFLECTIVE_ROUGHNESS …` и т.п.)

2022-06-14 13:41 UTC, DmitrySarafaniuk commented
Если есть желание, то чтобы долго не ждать расчет глобального освещения, можно сделать прогрессивную трассировку, где будут считаться не 1000 лучей на пиксель за цикл кадра, а по 1 и потом взвешенно суммировать их с текущим аккумулированным значением. `accumulated_radiance  = lerp(prev_radiance, new_radiance, 1.0f / (N + 1.0f));` N - текущая итерация.

2022-06-17 14:20 UTC, bi-te commented on engine/render/light_render.cpp
> +	const vec3& radiance, float dw, const Material& m)
++

2022-06-17 14:24 UTC, bi-te commented
Постепенная трассировка активируется кнопкой P

2022-06-27 05:00 UTC, mrindieperson commented
- сетку шариков сделай горизонтальной
- добавь пару кубиков

2022-06-27 05:00 UTC, mrindieperson requested changes

2022-06-27 05:00 UTC, mrindieperson commented on engine/Scene.cpp
> +						reflection(refl, 1, MAX_REFLECTION_DEPTH, MAX_PROCESS_DISTANCE),
А в других ветках с включенным GI почему smooth reflection нет

2022-06-27 05:00 UTC, mrindieperson commented on engine/Scene.cpp
> +	std::vector set(fibonacci_set(tests, 2 * rndm.get_real() * PI));
Не аллоцируй массив и не заполняй его каждый раз, его можно в Scene хранить просто (не в статической памяти, так как разное число может понадобится семплов, а тут Scene определяет уже конкретное число)

2022-06-27 05:00 UTC, mrindieperson commented on engine/Scene.cpp
> +	integral_ray.direction = reflect(-view, record.norm);
А зачем здесь reflect вектор в интеграле дополнительный? И ты как по итогу суммируешь семплы? просто складываешь? я не вижу где тут формула численного интегрирования прослеживается, только сумму семплов вижу

2022-06-27 05:00 UTC, mrindieperson commented on engine/Scene.cpp
> +	float dw = 1.f / (tests + 1.f);
а, ты передаёшь тут solidAngle. Но только это не solidAngle, потому что у полусферы solidAngle равен не 1.0, а 2PI, ты сумму поделил на N, но не умножил на площадь интегрирования

2022-06-27 05:00 UTC, mrindieperson commented on engine/Scene.cpp
> +}
Проверь своё интегрирование так: к color добавляй значение dot(N, sampleDir). То есть ты будешь интеграл косинуса по полусфере находить. В результате после деления на N и умножения на 2PI должно получиться просто PI (Поэтому в lambert диффуз там ещё делится на PI для нормализации энергии)

2022-06-27 05:00 UTC, mrindieperson commented on engine/Scene.cpp
> +					cook_torrance(color, refl.direction, record.norm, -ray.direction,
Вот только при гладком отражении у нас интеграл вырождается: G = 1.0 (нет шероховатостей), D = 1.0 (BRDF Cook-Torrance только в одном направлении не равно 0.0, то есть 100% спекуляра отражается в одном направлении), фактор нормализации пропадает вместе с интегралом, остаётся только Fresnel, тут не корректно полную BRDF использовать

2022-06-27 11:28 UTC, bi-te commented on engine/Scene.cpp
> +						reflection(refl, 1, MAX_REFLECTION_DEPTH, MAX_PROCESS_DISTANCE),
При обычном расчете интеграла дополнительно кидается доп луч, а при постепенной трассировке, там лучи кидаются в близости к идеальному отражению.

2022-06-27 11:28 UTC, bi-te commented on engine/Scene.cpp
> +	std::vector set(fibonacci_set(tests, 2 * rndm.get_real() * PI));
++

2022-06-27 11:29 UTC, bi-te commented on engine/Scene.cpp
> +					cook_torrance(color, refl.direction, record.norm, -ray.direction,
++

2022-06-27 11:54 UTC, bi-te commented on engine/Scene.cpp
> +	float dw = 1.f / (tests + 1.f);
++

2022-06-27 12:04 UTC, bi-te commented on engine/Scene.cpp
> +	integral_ray.direction = reflect(-view, record.norm);
reflect для того, чтобы были отражения

2022-06-27 14:13 UTC, mrindieperson commented on engine/Scene.cpp
> +					cook_torrance(color, refl.direction, record.norm, -ray.direction,
так а что ты тут исправил то, у тебя полноценная BRDF вызывается для этого отдельного луча

2022-06-27 14:17 UTC, mrindieperson commented on engine/Scene.cpp
> +	integral_ray.direction = reflect(-view, record.norm);
а если smooth reflection отключены? А какая глубина у тебя итерации для гладких отражений? вынеси гладкие отражения в отдельную функцию и считай их отдельно от всего и просто добавляй к результату. У тебя они сейчас дублируются в трёх местах, получаются, и нет рекурсии как таковой. Глубина рекурсии 1 нужна только для GI, для гладких отражений сделай минимум 4

2022-06-27 14:25 UTC, mrindieperson commented on engine/Scene.cpp
> +						reflection(refl, 1, MAX_REFLECTION_DEPTH, MAX_PROCESS_DISTANCE),
"при постепенной трассировке, там лучи кидаются в близости к идеальному отражению" - зачем? считай только GI прогрессивно. Гладкое отражение + отражение первичное от источников света 1 раз можно посчитать, а progressive GI в отдельный буффер сохранять. Потому что иначе я не понял как ты складываешь энергию уточнённого результата GI со всем остальным

2022-06-27 14:29 UTC, mrindieperson commented on engine/Scene.cpp
> +				integral_ray.direction = lerp(refl, random, m.roughness).normalized();
Ну это слишком уж хак

2022-06-29 10:55 UTC, bi-te commented on engine/Scene.cpp
> +				integral_ray.direction = lerp(refl, random, m.roughness).normalized();
++

2022-06-30 00:58 UTC, mrindieperson commented on engine/Scene.cpp
> +		color += f.cwiseProduct(reflcolor) * (MAX_REFLECTIVE_ROUGHNESS - m.roughness) * 10.f;
Убери эти константы 10.f, сделай формулу от MAX_REFLECTIVE_ROUGHNESS

2022-06-30 01:02 UTC, mrindieperson commented on engine/render/light_render.cpp
> +	float cosPhi = sqrtf(light_dist * light_dist - radius * radius) / light_dist;
light_dist  = max(light_dist, radius); для избегания NAN если внутри сферы источника света будет поверхность, будет тогда считаться что телесный угол равен всей полусфере

2022-06-30 01:10 UTC, mrindieperson commented on engine/Scene.cpp
> +		integral_ray.direction = (point * basis).normalized();
point на полусфере итак нормализована, после умножения на матрицу вращения не надо нормализовывать

2022-06-30 08:00 UTC, bi-te commented on engine/Scene.cpp
> +		color += f.cwiseProduct(reflcolor) * (MAX_REFLECTIVE_ROUGHNESS - m.roughness) * 10.f;
++

2022-06-30 08:00 UTC, bi-te commented on engine/render/light_render.cpp
> +	float cosPhi = sqrtf(light_dist * light_dist - radius * radius) / light_dist;
++

2022-06-30 08:00 UTC, bi-te commented on engine/Scene.cpp
> +		integral_ray.direction = (point * basis).normalized();
++

2022-07-01 18:27 UTC, mrindieperson approved these changes
Approved 👍

2022-07-02 12:07 UTC, DmitrySarafaniuk approved these changes
👍

2022-07-02 14:18 UTC, merged