Homework 7
bi-te/DLRenderEngine pull request #7
Opened 2022-08-23 09:47 UTC by bi-te

2022-08-23 19:41 UTC, DmitrySarafaniuk commented on shaders/post_process.hlsl
> +	float4 color = hdr.Sample(g_sampler, input.texcoord);
Здесь должен быть point семплер (сейчас выставлен linear) или можно использовать .Load(...).

2022-08-23 19:43 UTC, DmitrySarafaniuk commented
В sky.hlsl сейчас отличия описания IA от входящих данных в VS (указан float, поступает uint). Лучше сейчас найти, в чем причина.

2022-08-23 19:44 UTC, DmitrySarafaniuk commented
post_process.hlsl лучше переназови в resolve.hlsl (postProcess более общее понятие, да и со стороны C++ указан resolve(...)).

2022-08-23 19:44 UTC, DmitrySarafaniuk commented on engine/moving/TransformSystem.h
> +class TransformSystem
Не забывай, пожалуйста, указывать для синглтонов, что copy/move constructor/assignment operator удалены (например, для TransformSystem, LightSystem, ...).

2022-08-23 19:45 UTC, DmitrySarafaniuk commented on engine/render/EmissiveInstances.cpp
> +			Direct3D::instance().context4->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);
Это можно вынести до цикла.

2022-08-23 19:46 UTC, DmitrySarafaniuk commented on engine/render/LightSystem.cpp
> +		p_buffer.radiance = irradianceAtDistanceToRadiance(p_data.irradiance, p_data.light_range, p_data.radius);
Может, лучше было бы хранить это значение и просто менять его в случае изменения параметров источника. Если есть причины делать именно так, как сейчас, то можно оставить.

2022-08-23 19:47 UTC, DmitrySarafaniuk commented on engine/render/Material.h
> +	uint32_t hasMetallicTexture;
Пока что можно и так оставить, но лучше это всё вместе с uint32_t reverseNormalTextureY;  хранить в одном uint32_t (можно это сделать с помощью bit fields - в hlsl они тоже есть, но там нужна другая shader model, так что там просто будет один uint).

2022-08-23 19:48 UTC, DmitrySarafaniuk commented on engine/render/MaterialManager.cpp
>  		switch (texture.first)
Тут точно не нужны break;?

2022-08-23 19:49 UTC, DmitrySarafaniuk commented on shaders/opaque.hlsl
> +		normalize(world_normal.xyz));
Нормализацию лучше делать в PS.

2022-08-23 19:49 UTC, DmitrySarafaniuk commented on shaders/opaque.hlsl
> +			texNormal.y *= -1.f;
Сделай тоже тернарным оператором.

2022-08-23 19:50 UTC, DmitrySarafaniuk commented
Лучше логику со светом (по типу calc_x_light_pbr, closest_sphere_direction, и т.д.) вынести в отдельный Y.hlsli.
Аналогично из post_process.hlsl функции aces_tonemap(...), adjust_exposure(...), ... в PostProcessHelpers.hlsli.

2022-08-23 19:50 UTC, DmitrySarafaniuk commented on shaders/pbr_render.hlsli
> +#include "globals.hlsli"
Не забывай включаемые .hlsli файлы оборачивать в #ifndef X #define X #endif.

2022-08-23 19:55 UTC, DmitrySarafaniuk commented on shaders/pbr_render.hlsli
> +	if (cosV <= 0.f) cosV = 0.f;
В таких местах можно просто поставить float cosV = max(0.f, clamp(dot(normal, view), 0.f, 1.f));

2022-08-23 19:59 UTC, DmitrySarafaniuk commented on engine/render/LightSystem.cpp
> +	lBuffer->spotlightNum = spotlights.size();
Тут или в шейдере нужен max(xLights.size(), MAX_LIGHTS_NUMBER) (лучше тут). Иначе в шейдере можно читать за пределами буфера.

2022-08-24 16:05 UTC, bi-te commented on shaders/post_process.hlsl
> +	float4 color = hdr.Sample(g_sampler, input.texcoord);
++

2022-08-24 16:05 UTC, bi-te commented on engine/moving/TransformSystem.h
> +class TransformSystem
++

2022-08-24 16:05 UTC, bi-te commented on engine/render/EmissiveInstances.cpp
> +			Direct3D::instance().context4->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLELIST);
++

2022-08-24 16:07 UTC, bi-te commented on engine/render/Material.h
> +	uint32_t hasMetallicTexture;
++

2022-08-24 16:07 UTC, bi-te commented on engine/render/MaterialManager.cpp
>  		switch (texture.first)
++

2022-08-24 16:07 UTC, bi-te commented on shaders/opaque.hlsl
> +		normalize(world_normal.xyz));
++

2022-08-24 16:08 UTC, bi-te commented on shaders/opaque.hlsl
> +			texNormal.y *= -1.f;
++

2022-08-24 16:08 UTC, bi-te commented on shaders/pbr_render.hlsli
> +#include "globals.hlsli"
++

2022-08-24 16:08 UTC, bi-te commented on shaders/pbr_render.hlsli
> +	if (cosV <= 0.f) cosV = 0.f;
++

2022-08-24 16:08 UTC, bi-te commented on engine/render/LightSystem.cpp
> +	lBuffer->spotlightNum = spotlights.size();
++

2022-08-24 16:44 UTC, bi-te commented on engine/render/LightSystem.cpp
> +		p_buffer.radiance = irradianceAtDistanceToRadiance(p_data.irradiance, p_data.light_range, p_data.radius);
++

2022-08-28 21:31 UTC, mrindieperson requested changes

2022-08-28 21:31 UTC, mrindieperson commented on shaders/resolve.hlsl
> +	float4 color = hdr.Load(int3(input.texcoord.x * width, input.texcoord.y * height, 0));
SV_POSITION входная семантика имеет уже координаты пикселя в .xy компонентах, текстурные координаты не нужны тут

2022-08-28 21:31 UTC, mrindieperson commented on shaders/resolve.hlsl
> +	float ev100;
префикс g_ во всех униформах

2022-08-28 21:31 UTC, mrindieperson commented on shaders/resolve.hlsl
> +	res.pos = float4(-1.f + 4.f * (index == 1), 1.f - 4.f * (index == 2), 0.f, 1.f);
инклудь fullscreen шейдер из общего файла, тут и в sky

2022-08-28 21:31 UTC, mrindieperson commented on shaders/opaque.hlsl
> +Texture2D metallic: register(t3);
префиксы g_ ?

2022-08-28 21:31 UTC, mrindieperson commented on shaders/light_calculation.hlsli
> +	float attenuation = 1 - cosPhi;
Я вот здесь сделал ошибку в итоге и потом перепроверил в коде и убедился, что там действительно на 2PI надо умножать, мы интегрируем и нам нужна площадь интегрирования, а не просто attenuation от 0 до 1. Поправь

2022-08-28 21:31 UTC, mrindieperson commented on shaders/pbr_render.hlsli
> +	float cosL = dot(normal, light);
указывай всегда 2 вектора, cosL с чем? с N? или с H? гадать придётся

2022-08-28 21:31 UTC, mrindieperson commented on shaders/pbr_render.hlsli
> +	float cosH = dot(normal, h);
нет max с 0.001

2022-08-28 21:31 UTC, mrindieperson commented on shaders/pbr_render.hlsli
> +	float cosV = clamp(dot(normal, view), 0.f, 1.f);
нет max с 0.001

и не clamp(x, 0, 1), а saturate(x)

2022-08-28 21:31 UTC, mrindieperson commented on shaders/opaque.hlsl
> +	float3 model_scale: Inst_ModelScale;
это зачем?

2022-08-28 21:31 UTC, mrindieperson commented on engine/Scene.cpp
> +	LightSystem::instance().bind_lights();
если что, можно было 1 буффер PerFrame иметь и в bind_globals обращаться к LightSystem и читать источники. Но так думаю тоже норм, просто на каждую систему буффер иметь, наверное, смысла нет, если данные все всё равно одинаково 1 в кадр меняются

2022-08-28 21:35 UTC, mrindieperson commented on engine/render/MaterialManager.cpp
> +	assert(op_materials.count(name));
не count, а find с проверкой итератора

2022-08-28 21:37 UTC, mrindieperson commented on engine/Controller.cpp
> +            materials.get_opaque("assets/models/Knight/Fur_mat"),
Я не понял, как у тебя Metallness/Roughness и прочее всё грузится? Assimp эти текстуры за тебя не грузит, если что, их всех нужно самостоятельно указывать

2022-08-30 10:29 UTC, bi-te commented on shaders/resolve.hlsl
> +	float4 color = hdr.Load(int3(input.texcoord.x * width, input.texcoord.y * height, 0));
++

2022-08-30 10:29 UTC, bi-te commented on shaders/resolve.hlsl
> +	float ev100;
++

2022-08-30 10:29 UTC, bi-te commented on shaders/resolve.hlsl
> +	res.pos = float4(-1.f + 4.f * (index == 1), 1.f - 4.f * (index == 2), 0.f, 1.f);
++

2022-08-30 10:38 UTC, bi-te commented on shaders/opaque.hlsl
> +Texture2D metallic: register(t3);
++

2022-08-30 10:39 UTC, bi-te commented on shaders/light_calculation.hlsli
> +	float attenuation = 1 - cosPhi;
++

2022-08-30 10:41 UTC, bi-te commented on shaders/pbr_render.hlsli
> +	float cosL = dot(normal, light);
Так как с нормалью чаще всего делаются умножения, то я принял правило, что если указан лишь один вектор, то второй негласно является нормалью. Но исправил для лучшего понимания кода другими

2022-08-30 10:41 UTC, bi-te commented on shaders/pbr_render.hlsli
> +	float cosH = dot(normal, h);
++

2022-08-30 10:41 UTC, bi-te commented on shaders/pbr_render.hlsli
> +	float cosV = clamp(dot(normal, view), 0.f, 1.f);
++

2022-08-30 10:43 UTC, bi-te commented on shaders/opaque.hlsl
> +	float3 model_scale: Inst_ModelScale;
Это если скейлится модель неодинаково по всем осям, то это используется для убирания этого эффекта при работе с векторами.

2022-08-30 10:43 UTC, bi-te commented on engine/Scene.cpp
> +	LightSystem::instance().bind_lights();
++

2022-08-30 10:43 UTC, bi-te commented on engine/render/MaterialManager.cpp
> +	assert(op_materials.count(name));
++

2022-08-30 10:44 UTC, bi-te commented on engine/Controller.cpp
> +            materials.get_opaque("assets/models/Knight/Fur_mat"),
Текстуры грузятся в материалы при загрузке модели, а это я уже их достаю из системы материалов

2022-08-30 16:19 UTC, mrindieperson commented on shaders/pbr_render.hlsli
> +	float cosL = dot(normal, light);
ну нет, лучше одну лишнюю букву дописать чем вспоминать, где тут текстурная N, где геометрическая N, где H

2022-08-30 16:26 UTC, mrindieperson commented on shaders/opaque.hlsl
> +	world_normal = mul(input.model_transform, world_normal) / input.model_scale;
world_normal = mul(input.model_transform, world_normal / input.model_scale);

Масштабировать надо в ModelSpace

2022-08-30 16:41 UTC, mrindieperson commented on engine/render/OpaqueInstances.cpp
>  	direct.context4->PSSetShader(shader.pixelShader.Get(), nullptr, NULL);
ShaderManager::instance().operator()(opaqueShader.c_str()); - зачем через имя обращаться, уже при инициализации просто shared_ptr можно сохранить на шейдер

2022-08-30 16:41 UTC, mrindieperson commented on engine/render/OpaqueInstances.cpp
> +						TextureManager::instance().get_texture(material.normals.c_str()).GetAddressOf());
Аналогично не надо ни по каким мапам бегать при рендере, уже должны быть указатели в PerMaterial

2022-08-30 16:47 UTC, mrindieperson approved these changes
:+1: уппрув наперёд

2022-08-30 16:49 UTC, mrindieperson commented on shaders/light_calculation.hlsli
> +	float attenuation = (1 - sphereCos) * 2.f * PI;
переиеменуй тут и в других местах в solidAngle

2022-08-30 22:01 UTC, bi-te commented on shaders/light_calculation.hlsli
> +	float attenuation = (1 - sphereCos) * 2.f * PI;
++

2022-08-30 22:01 UTC, bi-te commented on engine/render/OpaqueInstances.cpp
> +						TextureManager::instance().get_texture(material.normals.c_str()).GetAddressOf());
++

2022-08-30 22:01 UTC, bi-te commented on engine/render/OpaqueInstances.cpp
>  	direct.context4->PSSetShader(shader.pixelShader.Get(), nullptr, NULL);
++

2022-08-30 22:01 UTC, bi-te commented on shaders/opaque.hlsl
> +	world_normal = mul(input.model_transform, world_normal) / input.model_scale;
++

2022-08-31 05:21 UTC, DmitrySarafaniuk approved these changes
👍

2022-08-31 12:41 UTC, bi-te commented on shaders/opaque.hlsl
> +	world_normal = mul(input.model_transform, world_normal) / input.model_scale;
++

2022-08-31 12:42 UTC, bi-te commented on engine/render/OpaqueInstances.cpp
>  	direct.context4->PSSetShader(shader.pixelShader.Get(), nullptr, NULL);
++

2022-08-31 12:42 UTC, bi-te commented on engine/render/OpaqueInstances.cpp
> +						TextureManager::instance().get_texture(material.normals.c_str()).GetAddressOf());
++

2022-08-31 12:43 UTC, bi-te commented on shaders/light_calculation.hlsli
> +	float attenuation = (1 - sphereCos) * 2.f * PI;
++

2022-08-31 12:44 UTC, merged