Homework 8
bi-te/DLRenderEngine pull request #8
Opened 2022-09-13 20:36 UTC by bi-te

2022-09-14 09:48 UTC, DmitrySarafaniuk commented
Видны shadow acne, попробуй понастраивать сдвиг, как писали в группе, и разрешение теневой карты. 
![image](https://user-images.githubusercontent.com/60367465/190121739-f75f15f2-ef91-465a-96c8-a6ac831381e9.png)

2022-09-14 09:50 UTC, DmitrySarafaniuk commented on engine/render/Direct11/RenderBuffer.cpp
> +	D3D11_RENDER_TARGET_VIEW_DESC rtv_desc;
Нельзя посмотреть снимок в RenderDoc (GPU device lost/hung), вроде бы проблема в MSAA.
Без MSAA то же самое, но из-за неинициализированного Texture2D.MipSlice "HDR Texture as RendreTargetView". Когда заполняешь различные X_DESC, то всегда используй ZeroMemory(&rtv_desc, sizeof(rtv_desc)) после объявления таких переменных.

2022-09-14 09:50 UTC, DmitrySarafaniuk commented on shaders/omnidirectional_shadows.hlsl
> +	float4 world_pos: Position;
Зачем в gs_out передавать float4 world_pos: Position;? Разве она потом где-то сохраняется или используется?

2022-09-14 09:51 UTC, DmitrySarafaniuk commented on shaders/omnidirectional_shadows.hlsl
> +	for (uint face = 0; face < 6; ++face)
Перед for в геометрическом шейдере можешь поставить [unroll], чтобы шейдер выполнялся быстрее, но компиляция будет медленнее.

2022-09-14 09:55 UTC, DmitrySarafaniuk commented
Только сейчас увидел, что в DynamicBuffer.cpp DynamicBuffer::map() возвращается ссылка на локальную переменную, лучше убрать &. Когда со временем захочется пересмотреть задания на других версиях компилятора или даже последующих стандартах языка здесь может быть ошибка.

Из того же разряда предупреждения о непрямом урезании переменных в hlsl при первой сборке. Сделай, пожалуйста,  чтобы этих предупреждений не было. В определенный момент с этим могут возникнуть проблемы и не будет понятно, где они.

2022-09-14 09:55 UTC, DmitrySarafaniuk commented on shaders/resolve.hlsl
> +	float3 colorSum;
colorSum не инициализирована.

2022-09-14 11:41 UTC, bi-te commented on shaders/resolve.hlsl
> +	float3 colorSum;
++

2022-09-14 11:42 UTC, bi-te commented on shaders/omnidirectional_shadows.hlsl
> +	for (uint face = 0; face < 6; ++face)
++

2022-09-14 11:43 UTC, bi-te commented on shaders/omnidirectional_shadows.hlsl
> +	float4 world_pos: Position;
Раньше использовалась, когда глубину самостоятельно вычислял, теперь убрал.

2022-09-14 11:43 UTC, bi-te commented on engine/render/Direct11/RenderBuffer.cpp
> +	D3D11_RENDER_TARGET_VIEW_DESC rtv_desc;
++

2022-09-18 18:41 UTC, mrindieperson commented on engine/Scene.cpp
> +		light_system.bind_point_shadow_light(light);
Как писал в чате, попробуй убрать этот внешний цикл с перебинживанием DSV

2022-09-18 18:41 UTC, mrindieperson commented on engine/Scene.cpp
> +		MeshSystem::instance().opaque_instances.mesh_render();
Тоже

2022-09-18 19:14 UTC, mrindieperson requested changes

2022-09-18 19:14 UTC, mrindieperson commented on shaders/opaque.hlsl
> +	for (uint pLight_ind = 0; pLight_ind < g_lighting.pointLightNum; ++pLight_ind)
Инкапсулируй всю эту итерацию и сумму отражения в light_calculation

2022-09-18 19:14 UTC, mrindieperson commented on shaders/light_calculation.hlsli
> +	float tex_size = 2.f * lv_pos.z / g_lighting.buffer_side;
Можно не делать отдельное умножение матрицы, у тебя есть же compare.w вместо Z, можно offset вычесть из него, чтобы приблизительно отменить offset. а можно и просто compare.z использовать и всё, супер точное нахождение размера пикселя не важно

light_view и light_proj в одну можно матрицу слить. в итоге всего 1 умножение в коде достаточно.

2022-09-19 10:51 UTC, bi-te commented on shaders/light_calculation.hlsli
> +	float tex_size = 2.f * lv_pos.z / g_lighting.buffer_side;
++

2022-09-19 10:52 UTC, bi-te commented on shaders/opaque.hlsl
> +	for (uint pLight_ind = 0; pLight_ind < g_lighting.pointLightNum; ++pLight_ind)
++

2022-09-19 10:53 UTC, bi-te commented on engine/Scene.cpp
> +		MeshSystem::instance().opaque_instances.mesh_render();
++

2022-09-19 10:53 UTC, bi-te commented on engine/Scene.cpp
> +		light_system.bind_point_shadow_light(light);
++

2022-09-19 20:54 UTC, mrindieperson commented on engine/Scene.cpp
> +	for (uint32_t light = 0; light < lightNum; light++)
Я говорил, что эти циклы с переключением униформ должны быть самым внутренним циклом

2022-09-19 21:44 UTC, mrindieperson commented on shaders/light_calculation.hlsli
> +	float2 reflectanceLUT = g_reflectance.Sample(g_linear_clamp_sampler, lut_coor).rg;
SampleLevel для 0 мипа используй, чекни, что семплер Clamp, а не Wrap

2022-09-20 16:00 UTC, bi-te commented on shaders/light_calculation.hlsli
> +	float2 reflectanceLUT = g_reflectance.Sample(g_linear_clamp_sampler, lut_coor).rg;
++

2022-09-20 16:00 UTC, bi-te commented on engine/Scene.cpp
> +	for (uint32_t light = 0; light < lightNum; light++)
++

2022-09-20 23:09 UTC, e-kabirov approved these changes
Исправь некоторые замечания которые я в ЛС отправил, но в целом хорошо, approved :+1:

2022-09-21 06:47 UTC, DmitrySarafaniuk approved these changes
👍

2022-09-21 08:25 UTC, merged